### ISSUE TITLE
Popover open slot prop on:mouseover doesn't work 

### ISSUE THREAD

**Issue by marydotdev** [rgossiaux/svelte-headlessui#122]
**Describe the bug**
The open slot prop doesn't work on:mouseover event, or any of the other mouse events I tested. The close prop works the way I expected the open prop to behave. 

**To Reproduce**
https://svelte.dev/repl/2398b1d868e6432899afe5d96230124f?version=3.46.4

**Library version**
^1.0.2

**Comment by rgossiaux** [comment]
The `open` slot prop describes whether or not the popover is open. It exists so that you can use it for conditional rendering in the component tree. You can't use it to control the state of the popover; slot props in Svelte are effectively read-only. 

If this component were to have a way of controlling the state like that (it doesn't), it would be via a regular prop, not a slot prop.

**Comment by marydotdev** [comment]
Ah okay, thanks for your quick response! I was able to get the desired behavior working with svelte-popperjs. Really appreciate your work!
