### ISSUE TITLE
Carve our own path?

### ISSUE THREAD

**Issue by ibn-akbar** [rgossiaux/svelte-headlessui#27]
I have been waiting for this for almost a year. At this point there's nothing wrong if we try not to make it 'official'.

- "Unofficial port of" sounds a bit experimental. it should be called simply "based on". That'll give us more freedom.
- Merge updates from Headless UI upstream without being restricted to it.
- Take inspiration from other projects, i.e., [renderless-svelte](https://github.com/stephane-vanraes/renderless-svelte)
- Tailwind is not required so it'll be good to keep docs and code examples agnostic and easy to follow for custom/component css, [Chota](https://github.com/jenil/chota), [Picnic](https://github.com/franciscop/picnic), [WindiCSS](https://github.com/windicss/windicss), etc.

**Comment by rgossiaux** [comment]
Thanks for the feedback!

I agree about keeping the docs generally agnostic to Tailwind CSS, and making the default examples with just normal vanilla CSS. I think this project can provide a lot of value to the broader Svelte ecosystem (which doesn't have a ton of component libraries yet) and it's important that this value doesn't seem like it depends on Tailwind CSS. 

At the same time, the project *also* provides a lot of value to people who want to use Tailwind UI specifically. Making it easy to use Tailwind UI with Svelte is in my mind one of the central use cases for the library. For that reason, I do intend on hewing very close to the upstream library. In particular, I'm overall not interested right now in adding new functionality (much less components) that doesn't exist upstream. From everything I've seen, Tailwind Labs were intending on working on Headless UI more after the new year; I'd rather spend the effort on this project towards keeping up with those changes rather than on doing something totally new--it's far higher ROI. Hope that makes sense.
