### ISSUE TITLE
Accessing Listbox value with slot property

### ISSUE THREAD

**Issue by Conceptiks** [rgossiaux/svelte-headlessui#32]
Hi there,

as someone who has never used React or Vue, it can be a challenge to crosscheck your documentation with the official headlessui docs. As such, I hope you don't mind a question (even if it seems very basic):

**When using Listbox, am I only able to access the value of the Listbox by listening to the component event?**
`on:change((e) => selectedValue = e.detail)` as per your example? 

This doesn't seem to work:
`
<Listbox as="div" let:value>
<ListboxButton>{value}</ListboxButton> //returns undefined
`

If the above doesn't work, how do I access/make use of the component API? What confuses me is that in the official React docs, "value" is listed as a prop. Does this not automatically mean that the prop is exposed? (https://headlessui.dev/react/listbox#component-api)

**Comment by rgossiaux** [comment]
Hey! Sorry you're having trouble with the documentation, I know it's not in a good state right now. Writing independent, Svelte-specific documentation is my next priority for this project, but in the meantime I'm happy to try to help with questions like this.

The way to convert the docs is that the props are the same in both libraries & the "render props" in React become slot props in Svelte; the `let:value` syntax in Svelte is for accessing a slot prop. For Listbox, `value` is a normal prop, not a slot prop, so that's why your example doesn't work. 

The way this component is designed (as well as most of the other components in the library) is that it doesn't manage its own state directly. You pass it a `value` prop that says which value is selected, and the component fires a change event when the user selects a new value, which you use to update the `value` prop. For example, something like:

```svelte
<script>
  let value;
</script>

<Listbox {value} on:change={(e) => value = e.detail}>
  <ListboxButton>{value ?? ""}</ListboxButton>
  <ListboxOptions>
    <ListboxOption value="Option A">Option A</ListboxOption>
    <ListboxOption value="Option B">Option B</ListboxOption>
    <ListboxOption value="Option C">Option C</ListboxOption>
  </ListboxOptions>
</Listbox>
```

It might seem a little unintuitive for it to work this way--why doesn't the Listbox just keep track of which item is selected instead of making you always tell it?--but it's more flexible, since it gives you total control over which item is selected in case you want to set it programmatically. 

Hope that makes sense, let me know if you have more questions!

**Comment by Conceptiks** [comment]
@rgossiaux  Thanks a lot for the detailed reply! I now have a better understanding of how to "read" the React docs and use your svelte components!
