### ISSUE TITLE
Components not rendered in normal Svelte project

### ISSUE THREAD

**Issue by jerriclynsjohn** [rgossiaux/svelte-headlessui#37]
Reproduction Repo: https://github.com/jerriclynsjohn/svelte-headlessui-test-repo.git

I'm trying to use this in a regular svelte project, I've set up a normal repo with only tailwindcss as the additional dependency, and still, when I try to import and use Switch it breaks.

Tested with the svelte kit and it works perfectly but doesn't work with a regular svelte SPA

**Comment by rgossiaux** [comment]
Thanks for the report. It's because there are a few `process.env.NODE_ENV` references in the code, and the SvelteKit `package` command (which is what I use to package this up for NPM) doesn't replace them. Then the packaging in your test repo also does not handle `process.env`, it seems.

IMO there's no reason why the `process.env` references should be in the end-user package, so I filed a bug with SvelteKit: https://github.com/sveltejs/kit/issues/3480

Depending on if/when we can get better handling of this in SvelteKit, I may add my own hacky find-and-replace step to the build process.

**Comment by jerriclynsjohn** [comment]
> Then the packaging in your test repo also does not handle `process.env`, it seems.

How can I handle this now, what should I do to make this work for now?

**Comment by rgossiaux** [comment]
I'll fix this in the next release (should be later today) by just adding some quick sed command to my release process or something. Hopefully we'll get some better support for this upstream in SvelteKit eventually.

**Comment by rgossiaux** [comment]
Just made a new release which fixes this.

**Comment by jerriclynsjohn** [comment]
Hey this worked, thank you. I really appreciate this!!!
