### ISSUE TITLE
Text Selection Broken in Dialogs

### ISSUE THREAD

**Issue by wilsonowilson** [rgossiaux/svelte-headlessui#39]
I noticed I can't select text in Dialogs on all browsers. This doesn't apply to input elements though.

https://user-images.githubusercontent.com/63465656/150507521-cf94fe7e-f5dd-42a8-a563-3abcb4be7bd9.mov

**Comment by rgossiaux** [comment]
Thanks, I can reproduce this as well. The `<FocusTrap>` component used in Dialogs is misbehaving here--not dissimilar to another focus bug open (#36 ). It feels like I'm missing something in how Headless UI is handling these focus events, because I'm having trouble seeing why this doesn't affect upstream too.

**Comment by rgossiaux** [comment]
Ahhhhhhhh...it's not that Headless UI is doing something magical, it's actually that SvelteKit is doing something nefarious. It adds a `tabIndex=-1` to the document body, and that ends up triggering extra focus events. That's responsible for both this bug and #36. 

Honestly I think SvelteKit is very much misbehaving here. Adding in this tabIndex to the document body has the potential to mess up a lot of stuff. Going to try to resolve this in SvelteKit if I can. In the meantime I think I need to add some hack to remove this if it's present.
